name: Fare Alerts

on:
  schedule:
    - cron: "0 13 * * *"   # runs daily at 1pm UTC (8am EST)
  workflow_dispatch:         # lets you run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python dtw_fare_alerts.py
